#!/bin/zsh
#
# Author:       Elizabeth Bodaneze 2021
# Description:  Download clipboard links
# Requires:     zsh, wget, xclip
# Usage:        get-here [.]
#               multiple files can be separated by new lines

[[ -n $1 ]] && cd $1

url_list=$(xclip -o -selection clipboard)

echo ${url_list} \
    | while read url ; do 
        filename=$(echo $url | rev | cut -d'/' -f1 | rev)

        # fix twitter file names
        if echo $url | grep "twimg" > /dev/null ; then
          filename=$(echo $filename | sed 's/\?format=/./;s/\&name=.*//')
        fi

        wget "${url}" --no-clobber -O "${filename}"
      done
