#!/bin/zsh
# put the computer to sleep after N seconds
# Elizabeth Bodaneze 2018


screen_lock() {
  sleep 15
  i3lock-color
  #xscreensaver-command -lock
}

interval=$1

if ! [[ -a /tmp/magic_suspend.pid.lock ]]; then
  echo $$ > /tmp/magic_suspend.pid.lock
  screen_lock &

  until (( interval == 0 )); do
    notify-send "Sleeping in T-$(converts -l $interval)"
    interval=$((interval/2))
    sleep $interval
  done
  systemctl suspend

elif [[ -a  /tmp/magic_suspend.pid.lock ]]; then
  kill $(</tmp/magic_suspend.pid.lock) && notify-send "Magic Suspend interrupted!"

fi

rm /tmp/magic_suspend.pid.lock
