#!/bin/zsh

call=${0##*/}

case $call in
  'mp32ogg')  __EXT=mp3  ;;
  'flac2ogg') __EXT=flac ;;
  ?) exit 1 ;;
esac

find . -type f -name "*.${__EXT}" -print0 | \
  parallel -0 --bar 'ffmpeg -loglevel error -i {} -c:a libvorbis -q:a 5 -vn {}.ogg && rm {}'

find . -name "*.${__EXT}.ogg" -exec bash -c 'mv "$1" "${1%.'${__EXT}'.ogg}".ogg' - '{}' \;
