#!/bin/zsh
#
# Author:       Elizabeth Bodaneze 2018
# Description:  Start a tmux or attach to session 0 if it exists
# Requires:     tmux
# Usage:        tmux_start

term_command=urxvt
keys=(+sb -name tmux -geometry 201x75 -e)

#term_command=xfce4-terminal 
#keys=(-I utilities-terminal --hide-menubar --maximize -x)

if sessions=$(tmux ls) ; then
  $term_command $keys tmux attach -c ${sessions:0:1} &
else
  $term_command $keys tmux &
fi

exit 0
