#!/bin/zsh
# source: https://askubuntu.com/a/571711
#         https://askubuntu.com/questions/104155/center-a-window-via-command-line

monitors=(DVI-I-0 DVI-D-0 HDMI-0)
#connected_monitors=(0 0 0)
xrandr=$(xrandr -d :0 | xargs)
i=0

for monitor in $monitors ; do
  echo $xrandr | grep "${monitor} connected" && (( connected_monitors = 2**i))
  ((i++))
done

IFS='x' read screenWidth screenHeight < <(xdpyinfo | grep dimensions | grep -o '[0-9x]*' | head -n1)

width=$(xdotool getactivewindow getwindowgeometry --shell | head -4 | tail -1 | sed 's/[^0-9]*//')
height=$(xdotool getactivewindow getwindowgeometry --shell | head -5 | tail -1 | sed 's/[^0-9]*//')

#newPosX=$((screenWidth/2-width/2))
curPosX=$(xdotool getmouselocation | cut -d' ' -f1 | cut -d':' -f2)

#if (( curPosX <= 768 )) ; then
  #newPosX=$((768/2-width/2))
  newPosX=$((1280/2-width/2))
#else
#  newPosX=$((768+1280/2-width/2))
#fi
newPosY=$((screenHeight/2-height/2))

xdotool getactivewindow windowmove "$newPosX" "$newPosY"
