#!/bin/zsh
#weather forecast wrapper by Elizabeth Bodaneze

#WTTRCITY=

error="wttr: invalid option -- $@\n\
Try 'wttr --help' for more information.\n"

weather_graph(){
  finger ${city_nospaces}~$cols@graph.no
  return 0
}

_weather(){
  curl -s "${v2}wttr.in$1"
  return 0
}

help_text="\
wttr - Gets the weather forecast from the internet.\n\
\n\
Options:\n\
    -g     - Outputs a temperature graph\n\
    -m     - Moon phase\n\
    -f     - Full weather forecast\n\
    -2     - Outputs a verbose graph
    -h     - this help screen\n\n\""

cols=$(tput cols)
(( cols > 158 )) && cols=158
(( cols < 126 )) && narrow="?n"

city_lower=$(echo $WTTRCITY | tr -t '[:upper:]' '[:lower:]')
city_underscores=$(echo $city_lower |  tr -t ' ' '_')
city_nospaces=$(echo $city_lower |  tr -d ' ')

if [[ -z $1 ]]; then
  _weather "/${city_underscores}?0q"
  exit 0
fi

while getopts ":gmfh2" opt; do
  case $opt in
    g) weather_graph;;
    m) _weather "/moon";;
    f) _weather "/${city_underscores}${narrow}";;
    2) v2="v2." ; _weather "/${city_underscores}" ;;
    h) printf $help_text; exit 0;;
    \?) printf $error; exit 1;;
  esac
done

#TODO: cache data
